### ISSUE TITLE
error: events.js:187

### ISSUE THREAD

**Issue by IlhanDelic** [IlhanDelic/satellite-server#1]
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND http://localhost:5000
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http://localhost:5000'

this error pops up and needs to be fixed in order to listen.

**Comment by IlhanDelic** [comment]
i had to install event listener with npm and now it works
